"""Tests for the RAG system."""

import json
from unittest.mock import Mock, patch

import pytest

from retrieval.config import DatasetType
from retrieval.models import AgentSpec, RetrievalResult
from retrieval.rag import (
    SYSTEM_PROMPT,
    AgentRAG,
    build_prompt,
    format_agent_output,
    parse_agent_response,
)
from retrieval.rag_config import LLMConfig, RAGConfig

# === Test Data ===

SAMPLE_AGENT = AgentSpec(
    agent_id="test_agent",
    display_name="Test Agent",
    persona="A helpful test agent",
    description="An agent for testing purposes",
    tools=["test_tool"],
)

SAMPLE_RETRIEVAL_RESULT = RetrievalResult(
    agent=SAMPLE_AGENT,
    score=0.95,
    rank=1,
)

SAMPLE_LLM_RESPONSE = json.dumps(
    {
        "agent_id": "generated_agent",
        "display_name": "Generated Agent",
        "persona": "A newly generated agent",
        "description": "This agent was generated by the LLM",
        "tools": ["tool1", "tool2"],
    }
)

SAMPLE_LLM_RESPONSE_MULTI = json.dumps(
    [
        {
            "agent_id": "agent_1",
            "display_name": "Agent One",
            "persona": "First agent",
            "description": "Description one",
            "tools": [],
        },
        {
            "agent_id": "agent_2",
            "display_name": "Agent Two",
            "persona": "Second agent",
            "description": "Description two",
            "tools": ["tool"],
        },
    ]
)


# === Tests for build_prompt ===


class TestBuildPrompt:
    """Tests for the build_prompt function."""

    def test_build_prompt_with_examples(self):
        """Test prompt building with examples."""
        examples = [SAMPLE_RETRIEVAL_RESULT]
        prompt = build_prompt("create a test agent", examples, num_agents=1)

        assert "create a test agent" in prompt
        assert "Test Agent" in prompt
        assert "test_agent" in prompt
        assert "Example 1:" in prompt
        assert "Generate ONE agent" in prompt

    def test_build_prompt_without_examples(self):
        """Test prompt building without examples."""
        prompt = build_prompt("create a test agent", [], num_agents=1)

        assert "create a test agent" in prompt
        assert "Example" not in prompt
        assert "Generate ONE agent" in prompt

    def test_build_prompt_multiple_agents(self):
        """Test prompt for multiple agent generation."""
        prompt = build_prompt("create agents", [], num_agents=3)

        assert "Generate 3 different agent specifications" in prompt
        assert "JSON array" in prompt

    def test_build_prompt_multiple_examples(self):
        """Test prompt with multiple examples."""
        examples = [
            RetrievalResult(agent=SAMPLE_AGENT, score=0.95, rank=1),
            RetrievalResult(
                agent=AgentSpec(
                    agent_id="second_agent",
                    display_name="Second Agent",
                    persona="Another agent",
                    description="Another description",
                    tools=[],
                ),
                score=0.85,
                rank=2,
            ),
        ]
        prompt = build_prompt("query", examples)

        assert "Example 1:" in prompt
        assert "Example 2:" in prompt
        assert "Test Agent" in prompt
        assert "Second Agent" in prompt


# === Tests for parse_agent_response ===


class TestParseAgentResponse:
    """Tests for the parse_agent_response function."""

    def test_parse_single_agent(self):
        """Test parsing a single agent response."""
        agents = parse_agent_response(SAMPLE_LLM_RESPONSE)

        assert len(agents) == 1
        assert agents[0]["agent_id"] == "generated_agent"
        assert agents[0]["display_name"] == "Generated Agent"

    def test_parse_multiple_agents(self):
        """Test parsing multiple agents response."""
        agents = parse_agent_response(SAMPLE_LLM_RESPONSE_MULTI)

        assert len(agents) == 2
        assert agents[0]["agent_id"] == "agent_1"
        assert agents[1]["agent_id"] == "agent_2"

    def test_parse_with_markdown_json_block(self):
        """Test parsing response wrapped in markdown code block."""
        response = f"```json\n{SAMPLE_LLM_RESPONSE}\n```"
        agents = parse_agent_response(response)

        assert len(agents) == 1
        assert agents[0]["agent_id"] == "generated_agent"

    def test_parse_with_markdown_block(self):
        """Test parsing response wrapped in generic markdown block."""
        response = f"```\n{SAMPLE_LLM_RESPONSE}\n```"
        agents = parse_agent_response(response)

        assert len(agents) == 1
        assert agents[0]["agent_id"] == "generated_agent"

    def test_parse_invalid_json_raises(self):
        """Test that invalid JSON raises ValueError."""
        with pytest.raises(ValueError) as exc_info:
            parse_agent_response("not valid json")

        assert "Failed to parse LLM response" in str(exc_info.value)

    def test_parse_with_whitespace(self):
        """Test parsing response with extra whitespace."""
        response = f"  \n\n{SAMPLE_LLM_RESPONSE}\n\n  "
        agents = parse_agent_response(response)

        assert len(agents) == 1


# === Tests for format_agent_output ===


class TestFormatAgentOutput:
    """Tests for the format_agent_output function."""

    def test_format_json_single(self):
        """Test JSON formatting for single agent."""
        agent = {"agent_id": "test", "display_name": "Test"}
        output = format_agent_output([agent], "json")

        parsed = json.loads(output)
        assert parsed["agent_id"] == "test"

    def test_format_json_multiple(self):
        """Test JSON formatting for multiple agents."""
        agents = [
            {"agent_id": "test1", "display_name": "Test 1"},
            {"agent_id": "test2", "display_name": "Test 2"},
        ]
        output = format_agent_output(agents, "json")

        parsed = json.loads(output)
        assert len(parsed) == 2

    def test_format_pretty_single(self):
        """Test pretty formatting for single agent."""
        agent = {
            "agent_id": "test",
            "display_name": "Test Agent",
            "description": "A test agent",
            "persona": "Helpful",
            "tools": ["tool1"],
        }
        output = format_agent_output([agent], "pretty")

        assert "ID: test" in output
        assert "Name: Test Agent" in output
        assert "Description: A test agent" in output
        assert "Persona: Helpful" in output
        assert "Tools: tool1" in output

    def test_format_pretty_multiple(self):
        """Test pretty formatting for multiple agents."""
        agents = [
            {"agent_id": "test1", "display_name": "Test 1"},
            {"agent_id": "test2", "display_name": "Test 2"},
        ]
        output = format_agent_output(agents, "pretty")

        assert "Agent 1" in output
        assert "Agent 2" in output

    def test_format_pretty_no_tools(self):
        """Test pretty formatting with no tools."""
        agent = {"agent_id": "test", "display_name": "Test", "tools": []}
        output = format_agent_output([agent], "pretty")

        assert "Tools: None" in output


# === Tests for RAGConfig ===


class TestRAGConfig:
    """Tests for RAGConfig."""

    def test_default_config(self):
        """Test default configuration values."""
        config = RAGConfig()

        assert config.num_agents_to_return == 1
        assert config.num_retrieved_for_context == 5
        assert config.output_format == "json"
        assert config.llm.model == "gpt-oss"

    def test_with_dataset(self):
        """Test creating config with specific dataset."""
        config = RAGConfig.with_dataset(DatasetType.ENG)

        assert config.retrieval.dataset_type == DatasetType.ENG.value

    def test_custom_llm_config(self):
        """Test custom LLM configuration."""
        llm = LLMConfig(
            model="custom-model",
            base_url="https://custom.api/v1",
            api_key="custom-key",
            temperature=0.5,
        )
        config = RAGConfig(llm=llm)

        assert config.llm.model == "custom-model"
        assert config.llm.base_url == "https://custom.api/v1"
        assert config.llm.temperature == 0.5


# === Tests for AgentRAG ===


class TestAgentRAG:
    """Tests for the AgentRAG class."""

    def test_initialization(self):
        """Test RAG initialization."""
        config = RAGConfig()
        rag = AgentRAG(config)

        assert rag.config == config
        assert not rag._initialized

    def test_available_datasets(self):
        """Test available datasets property."""
        rag = AgentRAG()
        datasets = rag.available_datasets

        assert "agents_eng" in datasets
        assert "all" in datasets

    def test_current_dataset(self):
        """Test current dataset property."""
        config = RAGConfig.with_dataset(DatasetType.ENG)
        rag = AgentRAG(config)

        assert rag.current_dataset == DatasetType.ENG.value

    def test_stats_uninitialized(self):
        """Test stats before initialization."""
        rag = AgentRAG()
        stats = rag.stats

        assert stats["initialized"] is False

    @patch("retrieval.rag.AgentRetriever")
    @patch("retrieval.rag.OpenAI")
    def test_initialize(self, mock_openai, mock_retriever):
        """Test RAG initialization."""
        rag = AgentRAG()
        rag.initialize()

        assert rag._initialized
        mock_retriever.assert_called_once()
        mock_openai.assert_called_once()

    @patch("retrieval.rag.AgentRetriever")
    @patch("retrieval.rag.OpenAI")
    def test_generate(self, mock_openai, mock_retriever):
        """Test agent generation."""
        # Setup mocks
        mock_retriever_instance = Mock()
        mock_retriever_instance.search.return_value = [SAMPLE_RETRIEVAL_RESULT]
        mock_retriever_instance.dataset_stats = {"total_records": 100}
        mock_retriever.return_value = mock_retriever_instance

        mock_client = Mock()
        mock_response = Mock()
        mock_response.choices = [Mock(message=Mock(content=SAMPLE_LLM_RESPONSE))]
        mock_client.chat.completions.create.return_value = mock_response
        mock_openai.return_value = mock_client

        # Test
        rag = AgentRAG()
        agents = rag.generate("create a test agent")

        assert len(agents) == 1
        assert agents[0]["agent_id"] == "generated_agent"
        mock_retriever_instance.search.assert_called_once()
        mock_client.chat.completions.create.assert_called_once()

    @patch("retrieval.rag.AgentRetriever")
    @patch("retrieval.rag.OpenAI")
    def test_search_only(self, mock_openai, mock_retriever):
        """Test search-only mode."""
        # Setup mocks
        mock_retriever_instance = Mock()
        mock_retriever_instance.search.return_value = [SAMPLE_RETRIEVAL_RESULT]
        mock_retriever.return_value = mock_retriever_instance

        # Test
        rag = AgentRAG()
        results = rag.search_only("test query", top_k=3)

        assert len(results) == 1
        assert results[0].agent.agent_id == "test_agent"
        mock_retriever_instance.search.assert_called_with("test query", top_k=3)

    @patch("retrieval.rag.AgentRetriever")
    @patch("retrieval.rag.OpenAI")
    def test_switch_dataset(self, mock_openai, mock_retriever):
        """Test dataset switching."""
        mock_retriever_instance = Mock()
        mock_retriever.return_value = mock_retriever_instance

        rag = AgentRAG()
        rag.initialize()
        rag.switch_dataset(DatasetType.ALL)

        mock_retriever_instance.switch_dataset.assert_called_with(DatasetType.ALL)


# === Integration-style tests (with mocked external calls) ===


class TestRAGIntegration:
    """Integration-style tests for the RAG system."""

    @patch("retrieval.rag.AgentRetriever")
    @patch("retrieval.rag.OpenAI")
    def test_full_generate_flow(self, mock_openai, mock_retriever):
        """Test the full generation flow."""
        # Setup retriever mock
        mock_retriever_instance = Mock()
        mock_retriever_instance.search.return_value = [
            RetrievalResult(
                agent=AgentSpec(
                    agent_id="similar_agent",
                    display_name="Similar Agent",
                    persona="A similar agent for context",
                    description="This is a similar agent",
                    tools=["tool"],
                ),
                score=0.9,
                rank=1,
            )
        ]
        mock_retriever.return_value = mock_retriever_instance

        # Setup LLM mock
        mock_client = Mock()
        generated_response = json.dumps(
            {
                "agent_id": "new_agent",
                "display_name": "New Agent",
                "persona": "A newly created agent",
                "description": "Created based on the query",
                "tools": ["new_tool"],
            }
        )
        mock_response = Mock()
        mock_response.choices = [Mock(message=Mock(content=generated_response))]
        mock_client.chat.completions.create.return_value = mock_response
        mock_openai.return_value = mock_client

        # Run the test
        config = RAGConfig(
            num_agents_to_return=1,
            num_retrieved_for_context=3,
        )
        rag = AgentRAG(config)

        agents = rag.generate("I need a code review agent")

        # Verify
        assert len(agents) == 1
        assert agents[0]["agent_id"] == "new_agent"

        # Check that retriever was called with correct params
        mock_retriever_instance.search.assert_called_with(
            "I need a code review agent",
            top_k=3,
        )

        # Check that LLM was called
        call_args = mock_client.chat.completions.create.call_args
        assert call_args.kwargs["model"] == "gpt-oss"
        assert len(call_args.kwargs["messages"]) == 2
        assert call_args.kwargs["messages"][0]["role"] == "system"
        assert call_args.kwargs["messages"][1]["role"] == "user"

    @patch("retrieval.rag.AgentRetriever")
    @patch("retrieval.rag.OpenAI")
    def test_generate_multiple_agents(self, mock_openai, mock_retriever):
        """Test generating multiple agents."""
        mock_retriever_instance = Mock()
        mock_retriever_instance.search.return_value = []
        mock_retriever.return_value = mock_retriever_instance

        mock_client = Mock()
        mock_response = Mock()
        mock_response.choices = [Mock(message=Mock(content=SAMPLE_LLM_RESPONSE_MULTI))]
        mock_client.chat.completions.create.return_value = mock_response
        mock_openai.return_value = mock_client

        config = RAGConfig(num_agents_to_return=2)
        rag = AgentRAG(config)

        agents = rag.generate("create agents")

        assert len(agents) == 2


# === System prompt tests ===


class TestSystemPrompt:
    """Tests for the system prompt."""

    def test_system_prompt_contains_required_fields(self):
        """Test that system prompt mentions all required agent fields."""
        assert "agent_id" in SYSTEM_PROMPT
        assert "display_name" in SYSTEM_PROMPT
        assert "persona" in SYSTEM_PROMPT
        assert "description" in SYSTEM_PROMPT
        assert "tools" in SYSTEM_PROMPT

    def test_system_prompt_mentions_json(self):
        """Test that system prompt mentions JSON output."""
        assert "JSON" in SYSTEM_PROMPT
